HeTest/Models/Car.cs
namespace HeTest.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Doors { get; set; }
        public string Color { get; set; }
        public decimal Price { get; set; }
    }
}

HeTest/Pages/Cars/ManageCar.cshtml.cs
using HeTest.Models;
using HeTest.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HeTest.Pages.Cars
{
    public enum Operation
    {
        Read,
        Update,
        Delete
    }

    [BindProperties(SupportsGet = true)]
    public class ManageCarModel : PageModel
    {
        private CarsRepository _repository;

        public ManageCarModel(CarsRepository repository)
        {
            operation = Operation.Read;
            _repository = repository;
        }

        [BindProperty]
        public Car car { get; set; }
        public string message { get; set; }
        public Operation operation { get; set; }

        public IActionResult OnPostFind()
        {
            operation = Operation.Read;

            car = _repository.Read(car);

            return Page();
        }

        public IActionResult OnPostUpdate(Car car)
        {
            operation = Operation.Update;

            _repository.Update(car);

            return Page();
        }

        public IActionResult OnPostDelete(int Id)
        {
            operation = Operation.Delete;

            _repository.Delete(Id);

            return Page();
        }
    }
}

HeTest/Pages/Cars/NewCar.cshtml.cs
using HeTest.Models;
using HeTest.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HeTest.Pages.Cars
{
    [BindProperties(SupportsGet = true)]
    public class NewCarModel : PageModel
    {
        private CarsRepository _repository;

        public NewCarModel(CarsRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Car? car { get; set; }

        public void OnPost()
        {
            if (car != null)
                car = _repository.Create(car);
        }
    }
}

HeTest/Pages/Cars/ManageCar.cshtml
@page
@model HeTest.Pages.Cars.ManageCarModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
	ViewData["Title"] = "HE - Finding a Car";
}

<div class="text-center">
	<h2>Cars Management</h2>
	<form method="post">

		<input asp-for="car.Id" value="@Model.car?.Id" type="hidden" />
		Make:
		<input asp-for="car.Make" value="@Model.car?.Make" />
		<br />
		Model:
		<input asp-for="car.Model" value="@Model.car?.Model" />
		<br />
		Year:
		<input asp-for="car.Year" value="@Model.car?.Year" />
		<br />
		Doors:
		<input asp-for="car.Doors" value="@Model.car?.Doors" />
		<br />
		Color:
		<input asp-for="car.Color" value="@Model.car?.Color" />
		<br />
		Price:
		<input asp-for="car.Price" value="@Model.car?.Price" />

		<hr />

		<button asp-page-handler="Find">Find</button>
		<br />
		<hr />
		@if (Model.operation.Equals(Operation.Read))
		{
			if (Model.car != null)
			{
				<button asp-page-handler="Update" asp-route-id="@Model.car">Update</button>
				<button asp-page-handler="Delete" asp-route-id="@Model.car.Id">Delete</button>
			}
			else
			{
				<p>Nothing found!</p>
			}
		}
		else if (Model.operation.Equals(Operation.Delete))
		{
			<p>Car deleted!</p>
		}
		else
		{
			<p>Car updated!</p>
		}

	</form>
</div>

HeTest/Pages/Cars/NewCar.cshtml
@page
@model HeTest.Pages.Cars.NewCarModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
	ViewData["Title"] = "HE - Creating New Car";
}

<div class="text-center">
	<h2>Add a Car</h2>
	<form method="post">

		Make:
		<input asp-for="car.Make" />
		<br />
		Model:
		<input asp-for="car.Model" />
		<br />
		Year:
		<input asp-for="car.Year" />
		<br />
		Doors:
		<input asp-for="car.Doors" />
		<br />
		Color:
		<input asp-for="car.Color" />
		<br />
		Price:
		<input asp-for="car.Price" />

		<hr />

		<input type="submit" value="Add" />

		@if (Model.car?.Id > 0)
		{
			<p>Car added successfully!</p>
		}

	</form>
</div>

HeTest/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HeTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HeTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cars/NewCar">Add Car</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cars/ManageCar">Manage a Car</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HeTest - <a href="https://github.com/lucaslima2106/health_equity_k_force" target="_blank">Repository Link</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>